version: '3.7'

services:
  carapp:
    image: demo-car:1.0
    environment:
      "CarApp:CarApiUrl": http://carapi/
      "CarApp:Vin": VINNY_JONES
  
  carapi:
    image: demo-carapi:1.0
    environment:
      "CarApi:UserApiUrl": http://userapi/
    expose:
      - "80"
    
  userapi:
    image: demo-userapi:1.0
    environment:
      "UserApi:CarApiUrl": http://carapi/
    expose:
      - "80"

  mobileapi:
      image: demo-mobileapi:1.0
      environment:
      "MobileApi:UserApiUrl": http://userapi/
      "MobileApi:CarApiUrl": http://carapi/
  
  mobileapp:
    image: demo-mobileapp:1.0
    environment:
      "MobileApp:MobileApiUrl": http://mobileapi/
      "MobileApp:UserId": "0xDEADBEEF"
      "MobileApp:Vin": "VINNY_JONES"