version: '3.7'

services:
  carapp_1:
    image: demo-car:1.0
    environment:
      "CarApp:CarApiUrl": http://carapi/
      "CarApp:Vin": VINNY_JONES
      
  carapp_2:
    image: demo-car:1.0
    environment:
      "CarApp:CarApiUrl": http://carapi/
      "CarApp:Vin": VINNY_JONES
      
  carapp_3:
    image: demo-car:1.0
    environment:
      "CarApp:CarApiUrl": http://carapi/
      "CarApp:Vin": VINNY_JONES
  
  carapi:
    image: demo-carapi:1.0
    environment:
      "CarApi:UserApiUrl": http://userapi/
    expose:
      - "80"
    
  userapi:
    image: demo-userapi:1.0
    environment:
      "UserApi:CarApiUrl": http://carapi/
    expose:
      - "80"

  mobileapi:
      image: demo-mobileapi:1.0
      environment:
        "USER_API_URL": http://userapi
        "CAR_API_URL": http://carapi
        PORT: 80
      expose:
        - "80"
  
  mobileapp_1:
    image: demo-mobileapp:1.0
    environment:
      "MobileApp:MobileApiUrl": http://mobileapi/
      "MobileApp:UserId": MR_USER
      "MobileApp:Vin": VINNY_JONES
  
  mobileapp_2:
    image: demo-mobileapp:1.0
    environment:
      "MobileApp:MobileApiUrl": http://mobileapi/
      "MobileApp:UserId": MR_USER
      "MobileApp:Vin": VINNY_JONES
  
  mobileapp_3:
    image: demo-mobileapp:1.0
    environment:
      "MobileApp:MobileApiUrl": http://mobileapi/
      "MobileApp:UserId": MR_USER
      "MobileApp:Vin": VINNY_JONES